// Mock data for demonstration purposes
export const mockProducts = [
  {
    id: "1",
    name: "Brazilian Straight Hair",
    sku: "BSH-001",
    category: "straight",
    hairType: "virgin",
    origin: "brazilian",
    lengths: [12, 14, 16, 18, 20, 22, 24],
    color: "Natural Black",
    texture: "Straight",
    pricePerBundle: 85,
    bulkPricing: [
      { minQuantity: 10, pricePerUnit: 75 },
      { minQuantity: 50, pricePerUnit: 65 },
      { minQuantity: 100, pricePerUnit: 55 },
    ],
    stockQuantity: 150,
    minOrderQuantity: 3,
    description: "Premium Brazilian straight hair bundles with natural shine and softness.",
    images: ["/beautiful-straight-black-human-hair-bundles.jpg"],
    isActive: true,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Deep Wave Hair Bundles",
    sku: "DWH-002",
    category: "wavy",
    hairType: "virgin",
    origin: "peruvian",
    lengths: [14, 16, 18, 20, 22, 24],
    color: "Natural Brown",
    texture: "Deep Wave",
    pricePerBundle: 95,
    bulkPricing: [
      { minQuantity: 10, pricePerUnit: 85 },
      { minQuantity: 50, pricePerUnit: 75 },
      { minQuantity: 100, pricePerUnit: 65 },
    ],
    stockQuantity: 120,
    minOrderQuantity: 3,
    description: "Luxurious deep wave hair with rich texture and natural bounce.",
    images: ["/deep-wave-human-hair-with-rich-texture-and-volume.jpg"],
    isActive: true,
    isFeatured: true,
  },
  {
    id: "3",
    name: "Curly Hair Bundles",
    sku: "CHB-003",
    category: "curly",
    hairType: "virgin",
    origin: "indian",
    lengths: [12, 14, 16, 18, 20],
    color: "Natural Black",
    texture: "Curly",
    pricePerBundle: 105,
    bulkPricing: [
      { minQuantity: 10, pricePerUnit: 95 },
      { minQuantity: 50, pricePerUnit: 85 },
      { minQuantity: 100, pricePerUnit: 75 },
    ],
    stockQuantity: 80,
    minOrderQuantity: 3,
    description: "Natural curly hair with defined curl pattern and volume.",
    images: ["/natural-curly-human-hair-with-defined-curl-pattern.jpg"],
    isActive: true,
    isFeatured: false,
  },
  {
    id: "4",
    name: "Lace Frontal 13x4",
    sku: "LF-004",
    category: "frontal",
    hairType: "virgin",
    origin: "brazilian",
    lengths: [12, 14, 16, 18, 20],
    color: "Natural Black",
    texture: "Straight",
    pricePerBundle: 125,
    bulkPricing: [
      { minQuantity: 5, pricePerUnit: 115 },
      { minQuantity: 20, pricePerUnit: 105 },
      { minQuantity: 50, pricePerUnit: 95 },
    ],
    stockQuantity: 60,
    minOrderQuantity: 1,
    description: "Premium lace frontal with ear-to-ear coverage and natural hairline.",
    images: ["/high-quality-lace-frontal-with-ear-to-ear-coverage.jpg"],
    isActive: true,
    isFeatured: true,
  },
]

export const mockOrders = [
  {
    id: "1",
    orderNumber: "KRD-2024-001",
    customerId: "customer1",
    customerName: "Sarah Johnson",
    status: "processing",
    paymentStatus: "paid",
    items: [
      {
        productId: "1",
        productName: "Brazilian Straight Hair",
        quantity: 6,
        length: 18,
        pricePerUnit: 75,
        totalPrice: 450,
      },
    ],
    totalAmount: 450,
    createdAt: new Date("2024-01-15"),
    shippingAddress: {
      street: "123 Beauty Ave",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
    },
  },
  {
    id: "2",
    orderNumber: "KRD-2024-002",
    customerId: "customer2",
    customerName: "Maria Rodriguez",
    status: "shipped",
    paymentStatus: "paid",
    items: [
      {
        productId: "2",
        productName: "Deep Wave Hair Bundles",
        quantity: 12,
        length: 20,
        pricePerUnit: 85,
        totalPrice: 1020,
      },
    ],
    totalAmount: 1020,
    createdAt: new Date("2024-01-10"),
    trackingNumber: "TRK123456789",
  },
]

export const mockInquiries = [
  {
    id: "1",
    customerName: "Jennifer Smith",
    email: "jennifer@salon.com",
    type: "bulk_order",
    subject: "Bulk Order Inquiry - 200 Bundles",
    message: "I need 200 bundles of Brazilian straight hair for my salon chain. What are your best bulk prices?",
    status: "new",
    priority: "high",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    customerName: "David Chen",
    email: "david@beautystore.com",
    type: "product",
    subject: "Custom Color Request",
    message: "Do you offer custom coloring services? I need blonde hair bundles.",
    status: "in_progress",
    priority: "medium",
    createdAt: new Date("2024-01-18"),
  },
]
